server:
    port: 8000
    host: localhost
    servlet:
        encoding:
            force: true
            enabled: true
            charset: UTF-8

spring:
    h2:
        console:
            enabled: true
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:url-test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:

    jpa:
        database: h2
        defer-datasource-initialization: true
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                ddl-auto: create
                query.in_clause_parameter_padding: true
                format_sql: true
                use_sql_comments: true
        database-platform: org.hibernate.dialect.MySQL5Dialect


    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace

